### ISSUE TITLE
个人网站做的不错

### ISSUE THREAD

**Issue by li-xinyang** [huang-chenyu/huang-chenyu.github.io#1]
100 个赞，写博客可以试试 Jekyll 和 Hexo，然后制作模板。模板的使用频率很高，可以让别人很快关注到你，当然也可以磨一磨你的技术。哥们，下个月 17 号就去谷歌啦，机票都定好啦。 😆

**Comment by huang-chenyu** [comment]
都是你的功劳啊，让我对前端产生了兴趣，去谷歌一定要抓好机会啊，被谷歌要了以后不要忘了我啊，我还指望着你的内推呢

**Comment by li-xinyang** [comment]
去申请 GitHub Education Power Pack 然后 去 Namecheap 买一个域名，然后去 CloudFlare 绑定 DNS，再去看看如何 GitHub Page 自定义域名。之后再去学一下 Hexo 搭建静态博客。你徒手写页面，后面会后悔的（难维护，难搜索，难更新，难分类）。如果你想练习网页制作，去做 Web App 去。小学生才做静态页面嘞。

:dancer:
